name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if different

  # Optional: Run the workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Ensure this matches the required Node.js version

      - name: Install dependencies
        run: yarn install

      - name: Build the site
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build  # Path to the build output directory

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write  # Required to deploy to GitHub Pages
      id-token: write  # Required for authentication

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2